# ansible-playbook deploy.yaml -i inventories/local --vault-id ~/.tokens/vault.txt

- hosts: build
  roles:
  - folder_deploy
  - docker_build
  - docker_push

- hosts: leader
  roles:
  - role: file_deploy
    vars:
    - src: settings.json.j2
  - docker_deploy
