# ansible-playbook run.yaml -i inventories/local --vault-id ~/.tokens/vault.txt

- hosts: localhost
  roles:
  - role: docker_build
    vars:
    - path: '{{ playbook_dir }}/..'
  - role: file_deploy
    vars:
    - src: settings.json.j2
  - role: docker_deploy
    vars:
    - with_registry_auth: false
